# CONNECTING CODES
CLIENT_HI = b"CLIENTHI"

NICKNAME  = b"NICK"
NONUSER = b"NONUSER"

PASSWORD  = b"PASSWD"
BADPASS = b"BADPASS"

# MESSAGE HISTORIC CODES
FETCH_CHANNELS = b"FETCHAN"
FETCH_DM       = b"FETCHDM"

# UTILITY CODES
CHAN    = b"CHAN"
BADCHAN = b"BADCHAN"

COMMAND = b"COMMAND"

OKCODE  = b"OKCODE"